### ISSUE TITLE
Error when using showtime.js with jQuery DatetimePicker

### ISSUE THREAD

**Issue by marcoaacoliveira** [Andrinoid/showtime.js#13]
I'm getting a strange error when using jquery datetimepicker with showtime.js, the selectable area don't expand so I cannot use properly the datepicker from jQuery. I belive its because the element is dynamically inserted.

Any idea how to solve this?

Thanks!

![error-showtimejs-jquery-datetimepicker](https://cloud.githubusercontent.com/assets/1794425/19891853/c0ca52d8-a020-11e6-886b-e77be21c1ae7.png)

**Comment by Andrinoid** [comment]
Hey @marcoantoniooliveira 
I'm guessing you would like the focus on both the input and the datepicker popup. In that case you can focus on multiple elements by giving it a node list

```
tour.show({
    element: document.querySelectorAll('.one, .two'),
})
```

demo: https://jsfiddle.net/3p6jbmzy/

I think you are right about the datepicker being dynamically created. In that case you need to wrap the option argument in a function.

```
tour.show(function() {
    return {
        element: document.querySelectorAll('.one, .two'),
    }
}
```

demo: https://jsfiddle.net/chw7n3bb/

Hope that helps. If it doesn't you could create a fiddle replicating your problem and I'll look into it

**Comment by marcoaacoliveira** [comment]
Hey @Andrinoid 

Thanks for the answer...

I forked your example and put a dynamically created element, yet its not working:
https://jsfiddle.net/marcoaacoliveira/4nex39qz/30/

**Comment by Andrinoid** [comment]
glad to help,
only problem I see in your fiddle, is when you click the button to start the tour, you remove the new element with the blur function. it works for if you remove the blur function.
![image](https://cloud.githubusercontent.com/assets/7255160/19986522/fe426f52-a20e-11e6-8e66-4ec978d29c08.png)

https://jsfiddle.net/4nex39qz/31/

let me know how it goes.

**Comment by marcoaacoliveira** [comment]
Hey @Andrinoid I had no prev experience with Fiddle but I belive you are seeing the wrong version. Check it out what happend when I put a dynamically element inserted on focus event:
![image](https://cloud.githubusercontent.com/assets/1794425/19987092/26ea87d0-a1f8-11e6-823f-d9d8393a396c.png)

Can you try to check it here? 
https://jsfiddle.net/marcoaacoliveira/4nex39qz/

Thank you again.

**Comment by Andrinoid** [comment]
ahh I see,
the problem is that showtime has already set it's focus when the new element is added to the DOM. You need to do this in two steps. check out the forked fiddle again. In this example I called tour.next() on focus witch grabs the new element.

https://jsfiddle.net/3esktbe8/

**Comment by Andrinoid** [comment]
btw, I did some performance fixes. So you might consider updating to the newest release for your project :)

**Comment by marcoaacoliveira** [comment]
@Andrinoid thanks again. I made some changes based in what you said and its working well. But when I updated the version I got the other places clickable... there is any way to block it again (a parameter or something), like in the showtime.js demo?

**Comment by Andrinoid** [comment]
@marcoantoniooliveira  I made some updates.
if you want to disable events you can do it like this.

```
tour.show({
    pointerEvents: 'all',
    element: document.querySelectorAll('input'),
    ...
})
```

for hijacking the click event you can do this

```
tour.show({
    focusClick: function() {
        alert('hey');
    },
    pointerEvents: 'all',
    element: document.querySelectorAll('input'),
    ...
})
```

[updated demo page](http://apps.tweecode.com/custom/showtime/)

**Comment by marcoaacoliveira** [comment]
@Andrinoid Great! Nice job, man. But with pointerEvents:'all' I cant click in any area, button with highlight included. There is a option to make only the highlight area of showtime clickable?

**Comment by Andrinoid** [comment]
No, sorry. The focus is a canvas covering the entire page. It's a valid request though and I'll look into it.
