### ISSUE TITLE
The dots indicating the modal steps should not appear when there is only one step

### ISSUE THREAD

**Issue by olitomas** [Andrinoid/showtime.js#7]
![screen shot 2016-05-12 at 15 41 46](https://cloud.githubusercontent.com/assets/6918659/15220765/33d5c880-1858-11e6-83b4-d9321086d067.png)

**Comment by Andrinoid** [comment]
if message is an array it will create a steps from it

``` js
tour.modal({
    title: 'My title',
    message: ['slide 1 text', 'slide 2 text'],
})
```

If you only want the modal you should give message a string

``` js
tour.modal({
    title: 'My title',
    message: 'My modal text'
})
```
