### ISSUE TITLE
Tooltip should not wait for animate end (or whatever its called)

### ISSUE THREAD

**Issue by olitomas** [Andrinoid/showtime.js#9]
On page load when the website has a lot going on the overlay fade-in can be really slow. The tooltip waits for the "animation end event" and as a result you have to wait quite a while before it shows up. When you are loading a modal then its not as apparent because the modal does not wait for the "animation end" event. ....I personally believe that the modal approach is better and think the tooltip should not wait for the "animation end" event.

**Comment by Andrinoid** [comment]
Ok I agree that there are cases it doesn't feel right to wait for the focus animation to complete. So I made an option for it. popoverTimer can be 'auto' or any number that represents delay in milliseconds.

``` js
var tour = new Showtime()
.show({
    element: document.querySelector('.one'),
    placement: 'left',
    content: '<p>This is an element</p>',
    popoverTimer: false
})
.show({
    element: document.querySelector('.two'),
    placement: 'left',
    content: '<p>This is an element</p>',
    popoverTimer: 'auto'
})
.show({
    element: document.querySelector('.three'),
    placement: 'left',
    content: '<p>This is an element</p>',
    popoverTimer: 5000
});
```

You can also add this to the global settings  in the showtime instance if thats what you want in all cases.

``` js
var tour = new Showtime({popoverTimer: false})
...
```
